// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BftProtoMsg.proto

package com.solace.samples.protocgenerated;

public final class BftProtoMsg {
  private BftProtoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OptionalDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.solace.samples.protocgenerated.OptionalData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string group = 1;</code>
     * @return The group.
     */
    java.lang.String getGroup();
    /**
     * <code>string group = 1;</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>string unit = 2;</code>
     * @return The unit.
     */
    java.lang.String getUnit();
    /**
     * <code>string unit = 2;</code>
     * @return The bytes for unit.
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    /**
     * <code>int32 speed = 3;</code>
     * @return The speed.
     */
    int getSpeed();

    /**
     * <code>int32 bearing = 4;</code>
     * @return The bearing.
     */
    int getBearing();
  }
  /**
   * <pre>
   * optional fields to specify for the messages 
   * </pre>
   *
   * Protobuf type {@code com.solace.samples.protocgenerated.OptionalData}
   */
  public static final class OptionalData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.solace.samples.protocgenerated.OptionalData)
      OptionalDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OptionalData.newBuilder() to construct.
    private OptionalData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionalData() {
      group_ = "";
      unit_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OptionalData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_OptionalData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_OptionalData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.class, com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.Builder.class);
    }

    public static final int GROUP_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object group_ = "";
    /**
     * <code>string group = 1;</code>
     * @return The group.
     */
    @java.lang.Override
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 1;</code>
     * @return The bytes for group.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNIT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object unit_ = "";
    /**
     * <code>string unit = 2;</code>
     * @return The unit.
     */
    @java.lang.Override
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      }
    }
    /**
     * <code>string unit = 2;</code>
     * @return The bytes for unit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPEED_FIELD_NUMBER = 3;
    private int speed_ = 0;
    /**
     * <code>int32 speed = 3;</code>
     * @return The speed.
     */
    @java.lang.Override
    public int getSpeed() {
      return speed_;
    }

    public static final int BEARING_FIELD_NUMBER = 4;
    private int bearing_ = 0;
    /**
     * <code>int32 bearing = 4;</code>
     * @return The bearing.
     */
    @java.lang.Override
    public int getBearing() {
      return bearing_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(group_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, group_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unit_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, unit_);
      }
      if (speed_ != 0) {
        output.writeInt32(3, speed_);
      }
      if (bearing_ != 0) {
        output.writeInt32(4, bearing_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(group_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, group_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unit_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, unit_);
      }
      if (speed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, speed_);
      }
      if (bearing_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, bearing_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.solace.samples.protocgenerated.BftProtoMsg.OptionalData)) {
        return super.equals(obj);
      }
      com.solace.samples.protocgenerated.BftProtoMsg.OptionalData other = (com.solace.samples.protocgenerated.BftProtoMsg.OptionalData) obj;

      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (!getUnit()
          .equals(other.getUnit())) return false;
      if (getSpeed()
          != other.getSpeed()) return false;
      if (getBearing()
          != other.getBearing()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnit().hashCode();
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + getSpeed();
      hash = (37 * hash) + BEARING_FIELD_NUMBER;
      hash = (53 * hash) + getBearing();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.solace.samples.protocgenerated.BftProtoMsg.OptionalData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * optional fields to specify for the messages 
     * </pre>
     *
     * Protobuf type {@code com.solace.samples.protocgenerated.OptionalData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.solace.samples.protocgenerated.OptionalData)
        com.solace.samples.protocgenerated.BftProtoMsg.OptionalDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_OptionalData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_OptionalData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.class, com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.Builder.class);
      }

      // Construct using com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        group_ = "";
        unit_ = "";
        speed_ = 0;
        bearing_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_OptionalData_descriptor;
      }

      @java.lang.Override
      public com.solace.samples.protocgenerated.BftProtoMsg.OptionalData getDefaultInstanceForType() {
        return com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.getDefaultInstance();
      }

      @java.lang.Override
      public com.solace.samples.protocgenerated.BftProtoMsg.OptionalData build() {
        com.solace.samples.protocgenerated.BftProtoMsg.OptionalData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.solace.samples.protocgenerated.BftProtoMsg.OptionalData buildPartial() {
        com.solace.samples.protocgenerated.BftProtoMsg.OptionalData result = new com.solace.samples.protocgenerated.BftProtoMsg.OptionalData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.solace.samples.protocgenerated.BftProtoMsg.OptionalData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.group_ = group_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.unit_ = unit_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.speed_ = speed_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.bearing_ = bearing_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.solace.samples.protocgenerated.BftProtoMsg.OptionalData) {
          return mergeFrom((com.solace.samples.protocgenerated.BftProtoMsg.OptionalData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.solace.samples.protocgenerated.BftProtoMsg.OptionalData other) {
        if (other == com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.getDefaultInstance()) return this;
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getUnit().isEmpty()) {
          unit_ = other.unit_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getSpeed() != 0) {
          setSpeed(other.getSpeed());
        }
        if (other.getBearing() != 0) {
          setBearing(other.getBearing());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                group_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                unit_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                speed_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                bearing_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object group_ = "";
      /**
       * <code>string group = 1;</code>
       * @return The group.
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group = 1;</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 1;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        group_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        group_ = getDefaultInstance().getGroup();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string group = 1;</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        group_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>string unit = 2;</code>
       * @return The unit.
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unit = 2;</code>
       * @return The bytes for unit.
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unit = 2;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        unit_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        unit_ = getDefaultInstance().getUnit();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 2;</code>
       * @param value The bytes for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        unit_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <code>int32 speed = 3;</code>
       * @return The speed.
       */
      @java.lang.Override
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>int32 speed = 3;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(int value) {

        speed_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 speed = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        speed_ = 0;
        onChanged();
        return this;
      }

      private int bearing_ ;
      /**
       * <code>int32 bearing = 4;</code>
       * @return The bearing.
       */
      @java.lang.Override
      public int getBearing() {
        return bearing_;
      }
      /**
       * <code>int32 bearing = 4;</code>
       * @param value The bearing to set.
       * @return This builder for chaining.
       */
      public Builder setBearing(int value) {

        bearing_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bearing = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBearing() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bearing_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.solace.samples.protocgenerated.OptionalData)
    }

    // @@protoc_insertion_point(class_scope:com.solace.samples.protocgenerated.OptionalData)
    private static final com.solace.samples.protocgenerated.BftProtoMsg.OptionalData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.solace.samples.protocgenerated.BftProtoMsg.OptionalData();
    }

    public static com.solace.samples.protocgenerated.BftProtoMsg.OptionalData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionalData>
        PARSER = new com.google.protobuf.AbstractParser<OptionalData>() {
      @java.lang.Override
      public OptionalData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OptionalData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.solace.samples.protocgenerated.BftProtoMsg.OptionalData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BftOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.solace.samples.protocgenerated.Bft)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string type = 2;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional string type = 2;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 2;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional double latitude = 3;</code>
     * @return Whether the latitude field is set.
     */
    boolean hasLatitude();
    /**
     * <code>optional double latitude = 3;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>optional double longitude = 4;</code>
     * @return Whether the longitude field is set.
     */
    boolean hasLongitude();
    /**
     * <code>optional double longitude = 4;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>optional double altitude = 5;</code>
     * @return Whether the altitude field is set.
     */
    boolean hasAltitude();
    /**
     * <code>optional double altitude = 5;</code>
     * @return The altitude.
     */
    double getAltitude();

    /**
     * <code>optional int64 updatedTime = 6;</code>
     * @return Whether the updatedTime field is set.
     */
    boolean hasUpdatedTime();
    /**
     * <code>optional int64 updatedTime = 6;</code>
     * @return The updatedTime.
     */
    long getUpdatedTime();

    /**
     * <code>optional int64 pubTime = 7;</code>
     * @return Whether the pubTime field is set.
     */
    boolean hasPubTime();
    /**
     * <code>optional int64 pubTime = 7;</code>
     * @return The pubTime.
     */
    long getPubTime();

    /**
     * <code>optional bool online = 8;</code>
     * @return Whether the online field is set.
     */
    boolean hasOnline();
    /**
     * <code>optional bool online = 8;</code>
     * @return The online.
     */
    boolean getOnline();

    /**
     * <code>optional int32 frequency = 9;</code>
     * @return Whether the frequency field is set.
     */
    boolean hasFrequency();
    /**
     * <code>optional int32 frequency = 9;</code>
     * @return The frequency.
     */
    int getFrequency();

    /**
     * <code>optional string name = 10;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 10;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 10;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
     * @return Whether the optionalData field is set.
     */
    boolean hasOptionalData();
    /**
     * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
     * @return The optionalData.
     */
    com.solace.samples.protocgenerated.BftProtoMsg.OptionalData getOptionalData();
    /**
     * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
     */
    com.solace.samples.protocgenerated.BftProtoMsg.OptionalDataOrBuilder getOptionalDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.solace.samples.protocgenerated.Bft}
   */
  public static final class Bft extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.solace.samples.protocgenerated.Bft)
      BftOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Bft.newBuilder() to construct.
    private Bft(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bft() {
      id_ = "";
      type_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Bft();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_Bft_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_Bft_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.solace.samples.protocgenerated.BftProtoMsg.Bft.class, com.solace.samples.protocgenerated.BftProtoMsg.Bft.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>optional string id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <code>optional string type = 2;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>optional string type = 2;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    private double latitude_ = 0D;
    /**
     * <code>optional double latitude = 3;</code>
     * @return Whether the latitude field is set.
     */
    @java.lang.Override
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional double latitude = 3;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 4;
    private double longitude_ = 0D;
    /**
     * <code>optional double longitude = 4;</code>
     * @return Whether the longitude field is set.
     */
    @java.lang.Override
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional double longitude = 4;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 5;
    private double altitude_ = 0D;
    /**
     * <code>optional double altitude = 5;</code>
     * @return Whether the altitude field is set.
     */
    @java.lang.Override
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional double altitude = 5;</code>
     * @return The altitude.
     */
    @java.lang.Override
    public double getAltitude() {
      return altitude_;
    }

    public static final int UPDATEDTIME_FIELD_NUMBER = 6;
    private long updatedTime_ = 0L;
    /**
     * <code>optional int64 updatedTime = 6;</code>
     * @return Whether the updatedTime field is set.
     */
    @java.lang.Override
    public boolean hasUpdatedTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 updatedTime = 6;</code>
     * @return The updatedTime.
     */
    @java.lang.Override
    public long getUpdatedTime() {
      return updatedTime_;
    }

    public static final int PUBTIME_FIELD_NUMBER = 7;
    private long pubTime_ = 0L;
    /**
     * <code>optional int64 pubTime = 7;</code>
     * @return Whether the pubTime field is set.
     */
    @java.lang.Override
    public boolean hasPubTime() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int64 pubTime = 7;</code>
     * @return The pubTime.
     */
    @java.lang.Override
    public long getPubTime() {
      return pubTime_;
    }

    public static final int ONLINE_FIELD_NUMBER = 8;
    private boolean online_ = false;
    /**
     * <code>optional bool online = 8;</code>
     * @return Whether the online field is set.
     */
    @java.lang.Override
    public boolean hasOnline() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional bool online = 8;</code>
     * @return The online.
     */
    @java.lang.Override
    public boolean getOnline() {
      return online_;
    }

    public static final int FREQUENCY_FIELD_NUMBER = 9;
    private int frequency_ = 0;
    /**
     * <code>optional int32 frequency = 9;</code>
     * @return Whether the frequency field is set.
     */
    @java.lang.Override
    public boolean hasFrequency() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int32 frequency = 9;</code>
     * @return The frequency.
     */
    @java.lang.Override
    public int getFrequency() {
      return frequency_;
    }

    public static final int NAME_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>optional string name = 10;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional string name = 10;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 10;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPTIONALDATA_FIELD_NUMBER = 11;
    private com.solace.samples.protocgenerated.BftProtoMsg.OptionalData optionalData_;
    /**
     * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
     * @return Whether the optionalData field is set.
     */
    @java.lang.Override
    public boolean hasOptionalData() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
     * @return The optionalData.
     */
    @java.lang.Override
    public com.solace.samples.protocgenerated.BftProtoMsg.OptionalData getOptionalData() {
      return optionalData_ == null ? com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.getDefaultInstance() : optionalData_;
    }
    /**
     * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
     */
    @java.lang.Override
    public com.solace.samples.protocgenerated.BftProtoMsg.OptionalDataOrBuilder getOptionalDataOrBuilder() {
      return optionalData_ == null ? com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.getDefaultInstance() : optionalData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeDouble(5, altitude_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt64(6, updatedTime_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt64(7, pubTime_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeBool(8, online_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeInt32(9, frequency_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, name_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeMessage(11, getOptionalData());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, altitude_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, updatedTime_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, pubTime_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, online_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, frequency_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, name_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getOptionalData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.solace.samples.protocgenerated.BftProtoMsg.Bft)) {
        return super.equals(obj);
      }
      com.solace.samples.protocgenerated.BftProtoMsg.Bft other = (com.solace.samples.protocgenerated.BftProtoMsg.Bft) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasLatitude() != other.hasLatitude()) return false;
      if (hasLatitude()) {
        if (java.lang.Double.doubleToLongBits(getLatitude())
            != java.lang.Double.doubleToLongBits(
                other.getLatitude())) return false;
      }
      if (hasLongitude() != other.hasLongitude()) return false;
      if (hasLongitude()) {
        if (java.lang.Double.doubleToLongBits(getLongitude())
            != java.lang.Double.doubleToLongBits(
                other.getLongitude())) return false;
      }
      if (hasAltitude() != other.hasAltitude()) return false;
      if (hasAltitude()) {
        if (java.lang.Double.doubleToLongBits(getAltitude())
            != java.lang.Double.doubleToLongBits(
                other.getAltitude())) return false;
      }
      if (hasUpdatedTime() != other.hasUpdatedTime()) return false;
      if (hasUpdatedTime()) {
        if (getUpdatedTime()
            != other.getUpdatedTime()) return false;
      }
      if (hasPubTime() != other.hasPubTime()) return false;
      if (hasPubTime()) {
        if (getPubTime()
            != other.getPubTime()) return false;
      }
      if (hasOnline() != other.hasOnline()) return false;
      if (hasOnline()) {
        if (getOnline()
            != other.getOnline()) return false;
      }
      if (hasFrequency() != other.hasFrequency()) return false;
      if (hasFrequency()) {
        if (getFrequency()
            != other.getFrequency()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasOptionalData() != other.hasOptionalData()) return false;
      if (hasOptionalData()) {
        if (!getOptionalData()
            .equals(other.getOptionalData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      if (hasAltitude()) {
        hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAltitude()));
      }
      if (hasUpdatedTime()) {
        hash = (37 * hash) + UPDATEDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUpdatedTime());
      }
      if (hasPubTime()) {
        hash = (37 * hash) + PUBTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPubTime());
      }
      if (hasOnline()) {
        hash = (37 * hash) + ONLINE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getOnline());
      }
      if (hasFrequency()) {
        hash = (37 * hash) + FREQUENCY_FIELD_NUMBER;
        hash = (53 * hash) + getFrequency();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasOptionalData()) {
        hash = (37 * hash) + OPTIONALDATA_FIELD_NUMBER;
        hash = (53 * hash) + getOptionalData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.solace.samples.protocgenerated.BftProtoMsg.Bft prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.solace.samples.protocgenerated.Bft}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.solace.samples.protocgenerated.Bft)
        com.solace.samples.protocgenerated.BftProtoMsg.BftOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_Bft_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_Bft_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.solace.samples.protocgenerated.BftProtoMsg.Bft.class, com.solace.samples.protocgenerated.BftProtoMsg.Bft.Builder.class);
      }

      // Construct using com.solace.samples.protocgenerated.BftProtoMsg.Bft.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOptionalDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        type_ = "";
        latitude_ = 0D;
        longitude_ = 0D;
        altitude_ = 0D;
        updatedTime_ = 0L;
        pubTime_ = 0L;
        online_ = false;
        frequency_ = 0;
        name_ = "";
        optionalData_ = null;
        if (optionalDataBuilder_ != null) {
          optionalDataBuilder_.dispose();
          optionalDataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.solace.samples.protocgenerated.BftProtoMsg.internal_static_com_solace_samples_protocgenerated_Bft_descriptor;
      }

      @java.lang.Override
      public com.solace.samples.protocgenerated.BftProtoMsg.Bft getDefaultInstanceForType() {
        return com.solace.samples.protocgenerated.BftProtoMsg.Bft.getDefaultInstance();
      }

      @java.lang.Override
      public com.solace.samples.protocgenerated.BftProtoMsg.Bft build() {
        com.solace.samples.protocgenerated.BftProtoMsg.Bft result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.solace.samples.protocgenerated.BftProtoMsg.Bft buildPartial() {
        com.solace.samples.protocgenerated.BftProtoMsg.Bft result = new com.solace.samples.protocgenerated.BftProtoMsg.Bft(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.solace.samples.protocgenerated.BftProtoMsg.Bft result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.latitude_ = latitude_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.longitude_ = longitude_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.altitude_ = altitude_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.updatedTime_ = updatedTime_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.pubTime_ = pubTime_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.online_ = online_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.frequency_ = frequency_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.name_ = name_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.optionalData_ = optionalDataBuilder_ == null
              ? optionalData_
              : optionalDataBuilder_.build();
          to_bitField0_ |= 0x00000400;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.solace.samples.protocgenerated.BftProtoMsg.Bft) {
          return mergeFrom((com.solace.samples.protocgenerated.BftProtoMsg.Bft)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.solace.samples.protocgenerated.BftProtoMsg.Bft other) {
        if (other == com.solace.samples.protocgenerated.BftProtoMsg.Bft.getDefaultInstance()) return this;
        if (other.hasId()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasType()) {
          type_ = other.type_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasUpdatedTime()) {
          setUpdatedTime(other.getUpdatedTime());
        }
        if (other.hasPubTime()) {
          setPubTime(other.getPubTime());
        }
        if (other.hasOnline()) {
          setOnline(other.getOnline());
        }
        if (other.hasFrequency()) {
          setFrequency(other.getFrequency());
        }
        if (other.hasName()) {
          name_ = other.name_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (other.hasOptionalData()) {
          mergeOptionalData(other.getOptionalData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 25: {
                latitude_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                longitude_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                altitude_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 48: {
                updatedTime_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                pubTime_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                online_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                frequency_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 82: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                input.readMessage(
                    getOptionalDataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 2;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string type = 2;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>optional double latitude = 3;</code>
       * @return Whether the latitude field is set.
       */
      @java.lang.Override
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional double latitude = 3;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional double latitude = 3;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {

        latitude_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional double latitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>optional double longitude = 4;</code>
       * @return Whether the longitude field is set.
       */
      @java.lang.Override
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional double longitude = 4;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional double longitude = 4;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {

        longitude_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional double longitude = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double altitude_ ;
      /**
       * <code>optional double altitude = 5;</code>
       * @return Whether the altitude field is set.
       */
      @java.lang.Override
      public boolean hasAltitude() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional double altitude = 5;</code>
       * @return The altitude.
       */
      @java.lang.Override
      public double getAltitude() {
        return altitude_;
      }
      /**
       * <code>optional double altitude = 5;</code>
       * @param value The altitude to set.
       * @return This builder for chaining.
       */
      public Builder setAltitude(double value) {

        altitude_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional double altitude = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000010);
        altitude_ = 0D;
        onChanged();
        return this;
      }

      private long updatedTime_ ;
      /**
       * <code>optional int64 updatedTime = 6;</code>
       * @return Whether the updatedTime field is set.
       */
      @java.lang.Override
      public boolean hasUpdatedTime() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int64 updatedTime = 6;</code>
       * @return The updatedTime.
       */
      @java.lang.Override
      public long getUpdatedTime() {
        return updatedTime_;
      }
      /**
       * <code>optional int64 updatedTime = 6;</code>
       * @param value The updatedTime to set.
       * @return This builder for chaining.
       */
      public Builder setUpdatedTime(long value) {

        updatedTime_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 updatedTime = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdatedTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        updatedTime_ = 0L;
        onChanged();
        return this;
      }

      private long pubTime_ ;
      /**
       * <code>optional int64 pubTime = 7;</code>
       * @return Whether the pubTime field is set.
       */
      @java.lang.Override
      public boolean hasPubTime() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int64 pubTime = 7;</code>
       * @return The pubTime.
       */
      @java.lang.Override
      public long getPubTime() {
        return pubTime_;
      }
      /**
       * <code>optional int64 pubTime = 7;</code>
       * @param value The pubTime to set.
       * @return This builder for chaining.
       */
      public Builder setPubTime(long value) {

        pubTime_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 pubTime = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPubTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        pubTime_ = 0L;
        onChanged();
        return this;
      }

      private boolean online_ ;
      /**
       * <code>optional bool online = 8;</code>
       * @return Whether the online field is set.
       */
      @java.lang.Override
      public boolean hasOnline() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional bool online = 8;</code>
       * @return The online.
       */
      @java.lang.Override
      public boolean getOnline() {
        return online_;
      }
      /**
       * <code>optional bool online = 8;</code>
       * @param value The online to set.
       * @return This builder for chaining.
       */
      public Builder setOnline(boolean value) {

        online_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool online = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearOnline() {
        bitField0_ = (bitField0_ & ~0x00000080);
        online_ = false;
        onChanged();
        return this;
      }

      private int frequency_ ;
      /**
       * <code>optional int32 frequency = 9;</code>
       * @return Whether the frequency field is set.
       */
      @java.lang.Override
      public boolean hasFrequency() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional int32 frequency = 9;</code>
       * @return The frequency.
       */
      @java.lang.Override
      public int getFrequency() {
        return frequency_;
      }
      /**
       * <code>optional int32 frequency = 9;</code>
       * @param value The frequency to set.
       * @return This builder for chaining.
       */
      public Builder setFrequency(int value) {

        frequency_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 frequency = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrequency() {
        bitField0_ = (bitField0_ & ~0x00000100);
        frequency_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 10;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional string name = 10;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 10;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 10;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 10;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private com.solace.samples.protocgenerated.BftProtoMsg.OptionalData optionalData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.solace.samples.protocgenerated.BftProtoMsg.OptionalData, com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.Builder, com.solace.samples.protocgenerated.BftProtoMsg.OptionalDataOrBuilder> optionalDataBuilder_;
      /**
       * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
       * @return Whether the optionalData field is set.
       */
      public boolean hasOptionalData() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
       * @return The optionalData.
       */
      public com.solace.samples.protocgenerated.BftProtoMsg.OptionalData getOptionalData() {
        if (optionalDataBuilder_ == null) {
          return optionalData_ == null ? com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.getDefaultInstance() : optionalData_;
        } else {
          return optionalDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
       */
      public Builder setOptionalData(com.solace.samples.protocgenerated.BftProtoMsg.OptionalData value) {
        if (optionalDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          optionalData_ = value;
        } else {
          optionalDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
       */
      public Builder setOptionalData(
          com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.Builder builderForValue) {
        if (optionalDataBuilder_ == null) {
          optionalData_ = builderForValue.build();
        } else {
          optionalDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
       */
      public Builder mergeOptionalData(com.solace.samples.protocgenerated.BftProtoMsg.OptionalData value) {
        if (optionalDataBuilder_ == null) {
          if (((bitField0_ & 0x00000400) != 0) &&
            optionalData_ != null &&
            optionalData_ != com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.getDefaultInstance()) {
            getOptionalDataBuilder().mergeFrom(value);
          } else {
            optionalData_ = value;
          }
        } else {
          optionalDataBuilder_.mergeFrom(value);
        }
        if (optionalData_ != null) {
          bitField0_ |= 0x00000400;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
       */
      public Builder clearOptionalData() {
        bitField0_ = (bitField0_ & ~0x00000400);
        optionalData_ = null;
        if (optionalDataBuilder_ != null) {
          optionalDataBuilder_.dispose();
          optionalDataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
       */
      public com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.Builder getOptionalDataBuilder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getOptionalDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
       */
      public com.solace.samples.protocgenerated.BftProtoMsg.OptionalDataOrBuilder getOptionalDataOrBuilder() {
        if (optionalDataBuilder_ != null) {
          return optionalDataBuilder_.getMessageOrBuilder();
        } else {
          return optionalData_ == null ?
              com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.getDefaultInstance() : optionalData_;
        }
      }
      /**
       * <code>.com.solace.samples.protocgenerated.OptionalData optionalData = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.solace.samples.protocgenerated.BftProtoMsg.OptionalData, com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.Builder, com.solace.samples.protocgenerated.BftProtoMsg.OptionalDataOrBuilder> 
          getOptionalDataFieldBuilder() {
        if (optionalDataBuilder_ == null) {
          optionalDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.solace.samples.protocgenerated.BftProtoMsg.OptionalData, com.solace.samples.protocgenerated.BftProtoMsg.OptionalData.Builder, com.solace.samples.protocgenerated.BftProtoMsg.OptionalDataOrBuilder>(
                  getOptionalData(),
                  getParentForChildren(),
                  isClean());
          optionalData_ = null;
        }
        return optionalDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.solace.samples.protocgenerated.Bft)
    }

    // @@protoc_insertion_point(class_scope:com.solace.samples.protocgenerated.Bft)
    private static final com.solace.samples.protocgenerated.BftProtoMsg.Bft DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.solace.samples.protocgenerated.BftProtoMsg.Bft();
    }

    public static com.solace.samples.protocgenerated.BftProtoMsg.Bft getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bft>
        PARSER = new com.google.protobuf.AbstractParser<Bft>() {
      @java.lang.Override
      public Bft parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Bft> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bft> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.solace.samples.protocgenerated.BftProtoMsg.Bft getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_solace_samples_protocgenerated_OptionalData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_solace_samples_protocgenerated_OptionalData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_solace_samples_protocgenerated_Bft_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_solace_samples_protocgenerated_Bft_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BftProtoMsg.proto\022\"com.solace.samples." +
      "protocgenerated\"K\n\014OptionalData\022\r\n\005group" +
      "\030\001 \001(\t\022\014\n\004unit\030\002 \001(\t\022\r\n\005speed\030\003 \001(\005\022\017\n\007b" +
      "earing\030\004 \001(\005\"\235\003\n\003Bft\022\017\n\002id\030\001 \001(\tH\000\210\001\001\022\021\n" +
      "\004type\030\002 \001(\tH\001\210\001\001\022\025\n\010latitude\030\003 \001(\001H\002\210\001\001\022" +
      "\026\n\tlongitude\030\004 \001(\001H\003\210\001\001\022\025\n\010altitude\030\005 \001(" +
      "\001H\004\210\001\001\022\030\n\013updatedTime\030\006 \001(\003H\005\210\001\001\022\024\n\007pubT" +
      "ime\030\007 \001(\003H\006\210\001\001\022\023\n\006online\030\010 \001(\010H\007\210\001\001\022\026\n\tf" +
      "requency\030\t \001(\005H\010\210\001\001\022\021\n\004name\030\n \001(\tH\t\210\001\001\022F" +
      "\n\014optionalData\030\013 \001(\01320.com.solace.sample" +
      "s.protocgenerated.OptionalDataB\005\n\003_idB\007\n" +
      "\005_typeB\013\n\t_latitudeB\014\n\n_longitudeB\013\n\t_al" +
      "titudeB\016\n\014_updatedTimeB\n\n\010_pubTimeB\t\n\007_o" +
      "nlineB\014\n\n_frequencyB\007\n\005_nameb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_solace_samples_protocgenerated_OptionalData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_solace_samples_protocgenerated_OptionalData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_solace_samples_protocgenerated_OptionalData_descriptor,
        new java.lang.String[] { "Group", "Unit", "Speed", "Bearing", });
    internal_static_com_solace_samples_protocgenerated_Bft_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_solace_samples_protocgenerated_Bft_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_solace_samples_protocgenerated_Bft_descriptor,
        new java.lang.String[] { "Id", "Type", "Latitude", "Longitude", "Altitude", "UpdatedTime", "PubTime", "Online", "Frequency", "Name", "OptionalData", "Id", "Type", "Latitude", "Longitude", "Altitude", "UpdatedTime", "PubTime", "Online", "Frequency", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
